version: '3.8'

services:
  # Instance 1: Port 3000
  patrol-app-3000:
    build:
      context: .
    image: dev1pci2025/tracking-people-front-end:latest
    container_name: patrol-app-3000
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_KEY=FujDuGTsyEXVwkKrtRgn52APwAVRGmPOiIRX8cffynDvIW35bJaGeH3NcH6HcSeK
    volumes:
      - .env:/app/.env
    ports:
      - "3000:3000"
    restart: always

  # Instance 2: Port 3031
  patrol-app-3031:
    build:
      context: .
    image: dev1pci2025/tracking-people-front-end:latest
    container_name: patrol-app-3031
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_KEY=T4OBTUILZPL59QNHF304QXU5RN1HZD9J
    volumes:
      - .env:/app/.env
    ports:
      - "3031:3000"
    restart: always
